<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <DebugType>portable</DebugType>
    <AssemblyName>ConsoleFramework</AssemblyName>
    <PackageId>Elwood.ConsoleFramework</PackageId>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.0.3</Version>
    <PackageProjectUrl>https://github.com/elw00d/consoleframework</PackageProjectUrl>
    <Authors />
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
  </ItemGroup>
</Project>