using System;
using ConsoleFramework.Controls;
using ConsoleFramework.Core;

namespace ConsoleFramework.Events;

public delegate void MouseEventHandler(object sender, MouseEventArgs e);
public delegate void MouseButtonEventHandler(object sender, MouseButtonEventArgs e);
public delegate void MouseWheelEventHandler(object sender, MouseWheelEventArgs e);

public enum MouseButtonState { Released, Pressed }
public enum MouseButton { Left, Middle, Right }

public class MouseWheelEventArgs : MouseEventArgs
{
    public int Delta { get; }

    public MouseWheelEventArgs(object source, RoutedEvent routedEvent, Point rawPosition,
        MouseButtonState leftButton, MouseButtonState middleButton,
        MouseButtonState rightButton, int delta)
        : base(source, routedEvent, rawPosition, leftButton, middleButton, rightButton)
    {
        Delta = delta;
    }
}

public class MouseButtonEventArgs : MouseEventArgs
{
    private readonly MouseButton button;
    private readonly int clickCount;
    private readonly bool autoRepeat;

    public MouseButtonEventArgs(object source, RoutedEvent routedEvent)
        : base(source, routedEvent) { }

    public MouseButtonEventArgs(object source, RoutedEvent routedEvent, Point rawPosition,
        MouseButtonState leftButton, MouseButtonState middleButton,
        MouseButtonState rightButton,
        MouseButton button, int clickCount = 1, bool autoRepeat = false)
        : base(source, routedEvent, rawPosition, leftButton, middleButton, rightButton)
    {
        this.button = button;
        this.clickCount = clickCount;
        this.autoRepeat = autoRepeat;
    }

    public MouseButtonState ButtonState => button switch
    {
        MouseButton.Left => LeftButton,
        MouseButton.Middle => MiddleButton,
        MouseButton.Right => RightButton,
        _ => throw new InvalidOperationException("Unexpected MouseButton value.")
    };

    public MouseButton ChangedButton => button;
    public int ClickCount => clickCount;

    /// <summary>
    /// Returns true if this event is autogenerated by timer tick
    /// (e.g. user presses and holds left mouse button).
    /// </summary>
    public bool AutoRepeat => autoRepeat;
}

public class MouseEventArgs : RoutedEventArgs
{
    public MouseEventArgs(object source, RoutedEvent routedEvent) : base(source, routedEvent) { }

    public MouseEventArgs(object source, RoutedEvent routedEvent, Point rawPosition,
        MouseButtonState leftButton, MouseButtonState middleButton, MouseButtonState rightButton)
        : base(source, routedEvent)
    {
        RawPosition = rawPosition;
        LeftButton = leftButton;
        MiddleButton = middleButton;
        RightButton = rightButton;
    }

    public Point RawPosition { get; }
    public MouseButtonState LeftButton { get; }
    public MouseButtonState MiddleButton { get; }
    public MouseButtonState RightButton { get; }

    /// <summary>
    /// Returns translated coords relative to the specified control.
    /// Can return negative values if the control is capturing mouse input.
    /// </summary>
    public Point GetPosition(Control relativeTo) =>
        Control.TranslatePoint(null, RawPosition, relativeTo);
}