using ConsoleFramework.Core;
using System;

namespace ConsoleFramework.Events
{
    public class MouseButtonEventArgs : MouseEventArgs
    {
        private readonly MouseButton button;
        private readonly int clickCount;
        private readonly bool autoRepeat;

        public MouseButtonEventArgs(object source, RoutedEvent routedEvent)
            : base(source, routedEvent) { }

        public MouseButtonEventArgs(object source, RoutedEvent routedEvent, Point rawPosition,
            MouseButtonState leftButton, MouseButtonState middleButton,
            MouseButtonState rightButton,
            MouseButton button, int clickCount = 1, bool autoRepeat = false)
            : base(source, routedEvent, rawPosition, leftButton, middleButton, rightButton)
        {
            this.button = button;
            this.clickCount = clickCount;
            this.autoRepeat = autoRepeat;
        }

        public MouseButtonState ButtonState => button switch
        {
            MouseButton.Left => LeftButton,
            MouseButton.Middle => MiddleButton,
            MouseButton.Right => RightButton,
            _ => throw new InvalidOperationException("Unexpected MouseButton value.")
        };

        public MouseButton ChangedButton => button;
        public int ClickCount => clickCount;

        /// <summary>
        /// Returns true if this event is autogenerated by timer tick
        /// (e.g. user presses and holds left mouse button).
        /// </summary>
        public bool AutoRepeat => autoRepeat;
    }
}
